export const GENERAL_CHANNEL = 'general';
export const N_MESSAGE_TO_FETCH = 25;
export const MIN_CONVERSATION_NAME_LENGTH = 3;
export const MAX_CONVERSATION_NAME_LENGTH = 15;
export const GAME_CONVO_NAME = 'game';
export const GAME_TOKEN_PREFIX = 'game-';
export const SYSTEM_USER_NAME = 'System';
export const SYSTEM_ERROR_NAME = 'SystemError'; // this is not a user
export const CONVO_NAME_MAX_SIZE = 10;
