export const SPLITPOINTS_ID = 'MC_SPLIT_POINTS';
export const EXCHANGEALETTER_ID = 'MC_EXCHANGE_LETTER';
export const PLACERANDOMBONUS_ID = 'MC_PLACE_RANDOM_BONUS';
export const EXCHANGEHORSE_ID = 'MC_EXCHANGE_HORSE';
export const SKIPNEXTTURN_ID = 'MC_SKIP_NEXT_TURN';

export const MAX_NUMBER_OF_MAGIC_CARD = 3;
export const NUMBER_OF_WORDS_FOR_MAGIC_CARD = 3;
